function generateChart() {
    var chart = AmCharts.makeChart("chartdiv", {
        "type": "serial",
        "theme": "dark",
        "marginRight": 40,
        "marginLeft": 40,
        "autoMarginOffset": 20,
        "mouseWheelZoomEnabled": true,
        "dataDateFormat": "YYYY-MM-DD",
        "valueAxes": [{
            "id": "v1",
            "axisAlpha": 0,
            "position": "left",
            "ignoreAxisWidth": true
        }],
        "balloon": {
            "borderThickness": 1,
            "shadowAlpha": 0
        },
        "graphs": [{
            "id": "g1",
            "balloon": {
                "drop": true,
                "adjustBorderColor": false,
                "color": "#ffffff"
            },
            "bullet": "round",
            "bulletBorderAlpha": 1,
            "bulletColor": "#FFFFFF",
            "bulletSize": 5,
            "hideBulletsCount": 50,
            "lineThickness": 2,
            "title": "red line",
            "useLineColorForBulletBorder": true,
            "valueField": "value",
            "balloonText": "<span style='font-size:18px;'>[[value]]</span>"
        },
        {
            "id": "g2",
            "balloon": {
                "drop": true,
                "adjustBorderColor": false,
                "color": "#ffffff"
            },
            "bullet": "round",
            "bulletBorderAlpha": 1,
            "bulletColor": "#FFFFFF",
            "bulletSize": 5,
            "hideBulletsCount": 50,
            "lineThickness": 2,
            "title": "red line",
            "useLineColorForBulletBorder": true,
            "valueField": "value2",
            "balloonText": "<span style='font-size:18px;'>[[value2]]</span>"
        }
        ],
        "chartScrollbar": {
            "graph": "g1",
            "oppositeAxis": false,
            "offset": 30,
            "scrollbarHeight": 80,
            "backgroundAlpha": 0,
            "selectedBackgroundAlpha": 0.1,
            "selectedBackgroundColor": "#888888",
            "graphFillAlpha": 0,
            "graphLineAlpha": 0.5,
            "selectedGraphFillAlpha": 0,
            "selectedGraphLineAlpha": 1,
            "autoGridCount": true,
            "color": "#AAAAAA"
        },
        "chartCursor": {
            "pan": true,
            "valueLineEnabled": true,
            "valueLineBalloonEnabled": true,
            "cursorAlpha": 1,
            "cursorColor": "#258cbb",
            "limitToGraph": "g1",
            "valueLineAlpha": 0.2,
            "valueZoomable": true
        },
        "valueScrollbar": {
            "oppositeAxis": false,
            "offset": 50,
            "scrollbarHeight": 10
        },
        "categoryField": "date",
        "categoryAxis": {
            "parseDates": true,
            "dashLength": 1,
            "minorGridEnabled": true
        },
        "export": {
            "enabled": true
        },
        "dataProvider": [{
            "date": "2012-07-27",
            "value": 13,
            "value2": 19
        }, {
            "date": "2012-07-28",
            "value": 11,
            "value2": 8
        }, {
            "date": "2012-07-29",
            "value": 15,
            "value2": 11
        }, {
            "date": "2012-07-30",
            "value": 16,
            "value2": 14
        }, {
            "date": "2012-07-31",
            "value": 18,
            "value2": 13
        }, {
            "date": "2012-08-01",
            "value": 13,
            "value2": 22
        }, {
            "date": "2012-08-02",
            "value": 22,
            "value2": 19
        }, {
            "date": "2012-08-03",
            "value": 23,
            "value2": 17
        }, {
            "date": "2012-08-04",
            "value": 20,
            "value2": 25
        }, {
            "date": "2012-08-05",
            "value": 17,
            "value2": 18
        }, {
            "date": "2012-08-06",
            "value": 16,
            "value2": 22
        }, {
            "date": "2012-08-07",
            "value": 18,
            "value2": 13
        }, {
            "date": "2012-08-08",
            "value": 21,
            "value2": 14
        }, {
            "date": "2012-08-09",
            "value": 26,
            "value2": 15
        }, {
            "date": "2012-08-10",
            "value": 24,
            "value2": 19
        }, {
            "date": "2012-08-11",
            "value": 29,
            "value2": 22
        }, {
            "date": "2012-08-12",
            "value": 32,
            "value2": 19
        }, {
            "date": "2012-08-13",
            "value": 18,
            "value2": 17
        }, {
            "date": "2012-08-14",
            "value": 24,
            "value2": 16
        }, {
            "date": "2012-08-15",
            "value": 22,
            "value2": 9
        }, {
            "date": "2012-08-16",
            "value": 18,
            "value2": 11
        }, {
            "date": "2012-08-17",
            "value": 19,
            "value2": 14
        }, {
            "date": "2012-08-18",
            "value": 14,
            "value2": 15
        }, {
            "date": "2012-08-19",
            "value": 15,
            "value2": 16
        }, {
            "date": "2012-08-20",
            "value": 15
        }, {
            "date": "2012-08-21",
            "value": 8,
            "value2": 14
        }, {
            "date": "2012-08-22",
            "value": 9,
            "value2": 15
        }, {
            "date": "2012-08-23",
            "value": 8,
            "value2": 26
        }, {
            "date": "2012-08-24",
            "value": 7,
            "value2": 11
        }, {
            "date": "2012-08-25",
            "value": 5,
            "value2": 4
        }, {
            "date": "2012-08-26",
            "value": 11,
            "value2": 19
        }, {
            "date": "2012-08-27",
            "value": 13,
            "value2": 15
        }, {
            "date": "2012-08-28",
            "value": 18,
            "value2": 19
        }, {
            "date": "2012-08-29",
            "value": 20,
            "value2": 22
        }, {
            "date": "2012-08-30",
            "value": 29,
            "value2": 18
        }, {
            "date": "2012-08-31",
            "value": 33,
            "value2": 19
        }, {
            "date": "2012-09-01",
            "value": 42,
            "value2": 17
        }, {
            "date": "2012-09-02",
            "value": 35,
            "value2": 16
        }, {
            "date": "2012-09-03",
            "value": 31,
            "value2": 19
        }, {
            "date": "2012-09-04",
            "value": 47,
            "value2": 36
        }, {
            "date": "2012-09-05",
            "value": 52,
            "value2": 22
        }, {
            "date": "2012-09-06",
            "value": 46,
            "value2": 34
        }, {
            "date": "2012-09-07",
            "value": 41,
            "value2": 19
        }, {
            "date": "2012-09-08",
            "value": 43,
            "value2": 18
        }, {
            "date": "2012-09-09",
            "value": 40,
            "value2": 34
        }, {
            "date": "2012-09-10",
            "value": 39,
            "value2": 29
        }, {
            "date": "2012-09-11",
            "value": 34,
            "value2": 27
        }, {
            "date": "2012-09-12",
            "value": 29,
            "value2": 19
        }, {
            "date": "2012-09-13",
            "value": 34,
            "value2": 26
        }, {
            "date": "2012-09-14",
            "value": 37,
            "value2": 22
        }, {
            "date": "2012-09-15",
            "value": 42,
            "value2": 27
        }, {
            "date": "2012-09-16",
            "value": 49,
            "value2": 15
        }, {
            "date": "2012-09-17",
            "value": 46,
            "value2": 36
        }, {
            "date": "2012-09-18",
            "value": 47,
            "value2": 20
        }, {
            "date": "2012-09-19",
            "value": 55,
            "value2": 25
        }, {
            "date": "2012-09-20",
            "value": 59,
            "value2": 45
        }, {
            "date": "2012-09-21",
            "value": 58,
            "value2": 36
        }, {
            "date": "2012-09-22",
            "value": 57,
            "value2": 24
        }, {
            "date": "2012-09-23",
            "value": 61,
            "value2": 36
        }, {
            "date": "2012-09-24",
            "value": 59,
            "value2": 42
        }, {
            "date": "2012-09-25",
            "value": 67,
            "value2": 36
        }, {
            "date": "2012-09-26",
            "value": 65,
            "value2": 19
        }, {
            "date": "2012-09-27",
            "value": 61,
            "value2": 45
        }, {
            "date": "2012-09-28",
            "value": 66,
            "value2": 35
        }, {
            "date": "2012-09-29",
            "value": 69,
            "value2": 24
        }]
    });

    chart.addListener("rendered", zoomChart);

    zoomChart();

    function zoomChart() {
        chart.zoomToIndexes(chart.dataProvider.length - 40, chart.dataProvider.length - 1);
    }

}